general:
  num_periods: 2
  num_scenarios: 5
  num_generators: 5
  num_tiers: 4
  num_storage: 0

data_paths:
  generator_csv: "data/system/gen.csv"
  storage_csv: "data/system/storage.csv"
  demand_csv: "data/system/DAY_AHEAD_regional_load.csv"

solver:
  name: "cplex"
  executable: "C:/Program Files/IBM/ILOG/CPLEX_Studio2212/cplex/bin/x64_win64/cplex"
  options:
    tee: true
